# Generated by Django 2.0.2 on 2018-04-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresourse',
            old_name='name',
            new_name='CourseResoursename',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='lessonname',
        ),
    ]
